/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['.section-margin[_ngcontent-%COMP%]{\n    margin-bottom: 10px;\n}'];
//# sourceMappingURL=radio-button.component.css.shim.ngstyle.js.map