/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/radio-button/radio-button.module';
import * as i2 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/cdk';
import * as i5 from '@angular/platform-browser';
import * as i6 from '@angular/material';
import * as i7 from '@angular/forms';
import * as i8 from '@angular/router';
import * as i9 from '../../../../src/app/shared/shared.module';
import * as i10 from '../../../../src/app/pagination/pagination.model';
import * as i11 from '../../../../src/app/forms/productForm/form.module';
import * as i12 from '../../../../src/app/forms/salesForm/sales-form.module';
import * as i13 from '../../../../src/app/forms/labelForm/label-form.module';
import * as i14 from '../../../../src/app/forms/searchAllForm/search-all.module';
import * as i15 from '../../../../src/app/forms-center/forms-center.module';
export const RadioButtonModuleNgFactory:i0.NgModuleFactory<i1.RadioButtonModule> = i0.ɵcmf(i1.RadioButtonModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MdDialogContainerNgFactory,i2.MdDatepickerContentNgFactory]],[3,
              i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(6144,i4.DIR_DOCUMENT,(null as any),[i5.DOCUMENT]),
          i0.ɵmpd(4608,i4.Directionality,i4.Directionality,[[2,i4.DIR_DOCUMENT]]),
          i0.ɵmpd(4608,i4.Platform,i4.Platform,([] as any[])),i0.ɵmpd(5120,i6.ScrollDispatcher,
              i6.ɵe,[[3,i6.ScrollDispatcher],i0.NgZone,i4.Platform]),i0.ɵmpd(5120,
              i6.ViewportRuler,i6.ɵc,[[3,i6.ViewportRuler],i6.ScrollDispatcher]),i0.ɵmpd(4608,
              i6.ScrollStrategyOptions,i6.ScrollStrategyOptions,[i6.ScrollDispatcher,
                  i6.ViewportRuler]),i0.ɵmpd(5120,i6.UniqueSelectionDispatcher,i6.ɵh,
              [[3,i6.UniqueSelectionDispatcher]]),i0.ɵmpd(5120,i6.FocusOriginMonitor,
              i6.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,i6.FocusOriginMonitor],
                  i0.NgZone,i4.Platform]),i0.ɵmpd(4608,i7.FormBuilder,i7.FormBuilder,
              ([] as any[])),i0.ɵmpd(4608,i7.ɵi,i7.ɵi,([] as any[])),i0.ɵmpd(4608,
              i4.InteractivityChecker,i4.InteractivityChecker,[i4.Platform]),i0.ɵmpd(4608,
              i4.FocusTrapFactory,i4.FocusTrapFactory,[i4.InteractivityChecker,i4.Platform,
                  i0.NgZone]),i0.ɵmpd(5120,i4.LiveAnnouncer,i4.LIVE_ANNOUNCER_PROVIDER_FACTORY,
              [[3,i4.LiveAnnouncer],[2,i4.LIVE_ANNOUNCER_ELEMENT_TOKEN],i4.Platform]),
          i0.ɵmpd(5120,i6.OverlayContainer,i6.ɵa,[[3,i6.OverlayContainer]]),i0.ɵmpd(4608,
              i6.ɵt,i6.ɵt,[i6.ViewportRuler]),i0.ɵmpd(4608,i6.Overlay,i6.Overlay,[i6.ScrollStrategyOptions,
              i6.OverlayContainer,i0.ComponentFactoryResolver,i6.ɵt,i0.ApplicationRef,
              i0.Injector,i0.NgZone]),i0.ɵmpd(4608,i5.HAMMER_GESTURE_CONFIG,i5.HammerGestureConfig,
              ([] as any[])),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(5120,
              i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,
              ([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i5.DomSanitizer,i5.ɵe,[i3.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i5.DomSanitizer]),i0.ɵmpd(5120,i5.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i5.ɵDomEventsPlugin(p0_0),new i5.ɵKeyEventsPlugin(p1_0),
                    new i5.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i3.DOCUMENT,i3.DOCUMENT,i3.DOCUMENT,i5.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i5.EventManager,i5.EventManager,[i5.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i5.ɵDomSharedStylesHost,i5.ɵDomSharedStylesHost,[i3.DOCUMENT]),
          i0.ɵmpd(4608,i5.ɵDomRendererFactory2,i5.ɵDomRendererFactory2,[i5.EventManager,
              i5.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i5.ɵDomRendererFactory2]),i0.ɵmpd(6144,i5.ɵSharedStylesHost,(null as any),
              [i5.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i5.Meta,i5.Meta,[i3.DOCUMENT]),i0.ɵmpd(4608,
              i5.Title,i5.Title,[i3.DOCUMENT]),i0.ɵmpd(4608,i3.CurrencyPipe,i3.CurrencyPipe,
              [i0.LOCALE_ID]),i0.ɵmpd(4608,i6.MdDialog,i6.MdDialog,[i6.Overlay,i0.Injector,
              [2,i3.Location],[3,i6.MdDialog]]),i0.ɵmpd(4608,i6.MdDatepickerIntl,i6.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,([] as any[])),
          i0.ɵmpd(512,i6.CompatibilityModule,i6.CompatibilityModule,([] as any[])),
          i0.ɵmpd(512,i4.BidiModule,i4.BidiModule,([] as any[])),i0.ɵmpd(256,i6.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i6.MdCommonModule,i6.MdCommonModule,
              [[2,i5.DOCUMENT],[2,i6.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i4.PlatformModule,
              i4.PlatformModule,([] as any[])),i0.ɵmpd(512,i6.ScrollDispatchModule,
              i6.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i6.MdRippleModule,
              i6.MdRippleModule,([] as any[])),i0.ɵmpd(512,i6.MdRadioModule,i6.MdRadioModule,
              ([] as any[])),i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,[[2,i8.ɵa],
              [2,i8.Router]]),i0.ɵmpd(512,i7.ɵba,i7.ɵba,([] as any[])),i0.ɵmpd(512,
              i7.ReactiveFormsModule,i7.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,
              i7.FormsModule,i7.FormsModule,([] as any[])),i0.ɵmpd(512,i6.MdCardModule,
              i6.MdCardModule,([] as any[])),i0.ɵmpd(512,i6.MdProgressBarModule,i6.MdProgressBarModule,
              ([] as any[])),i0.ɵmpd(512,i4.A11yModule,i4.A11yModule,([] as any[])),
          i0.ɵmpd(512,i4.PortalModule,i4.PortalModule,([] as any[])),i0.ɵmpd(512,i6.OverlayModule,
              i6.OverlayModule,([] as any[])),i0.ɵmpd(512,i6.MdSidenavModule,i6.MdSidenavModule,
              ([] as any[])),i0.ɵmpd(512,i6.StyleModule,i6.StyleModule,([] as any[])),
          i0.ɵmpd(512,i6.MdSliderModule,i6.MdSliderModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i5.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any) => {
                return [i5.ɵc(p0_0,p0_1)];
              },[[2,i5.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i5.BrowserModule,i5.BrowserModule,[[3,i5.BrowserModule]]),i0.ɵmpd(512,
              i9.SharedModule,i9.SharedModule,([] as any[])),i0.ɵmpd(512,i10.PaginationModelModule,
              i10.PaginationModelModule,([] as any[])),i0.ɵmpd(512,i11.FormModule,
              i11.FormModule,([] as any[])),i0.ɵmpd(512,i6.MdInputModule,i6.MdInputModule,
              ([] as any[])),i0.ɵmpd(512,i6.MdButtonModule,i6.MdButtonModule,([] as any[])),
          i0.ɵmpd(512,i6.MdSelectionModule,i6.MdSelectionModule,([] as any[])),i0.ɵmpd(512,
              i6.MdOptionModule,i6.MdOptionModule,([] as any[])),i0.ɵmpd(512,i6.MdSelectModule,
              i6.MdSelectModule,([] as any[])),i0.ɵmpd(512,i6.MdDialogModule,i6.MdDialogModule,
              ([] as any[])),i0.ɵmpd(512,i6.MdDatepickerModule,i6.MdDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i12.SalesFormModule,i12.SalesFormModule,([] as any[])),
          i0.ɵmpd(512,i13.LabelFormModule,i13.LabelFormModule,([] as any[])),i0.ɵmpd(512,
              i14.SearchAllModule,i14.SearchAllModule,([] as any[])),i0.ɵmpd(512,i15.FormsCenterModule,
              i15.FormsCenterModule,([] as any[])),i0.ɵmpd(512,i1.RadioButtonModule,
              i1.RadioButtonModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcm9tYXJpby9hbmd1bGFyYXBpL3NyYy9hcHAvcmFkaW8tYnV0dG9uL3JhZGlvLWJ1dHRvbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9yb21hcmlvL2FuZ3VsYXJhcGkvc3JjL2FwcC9yYWRpby1idXR0b24vcmFkaW8tYnV0dG9uLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
