/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['.DivHeader[_ngcontent-%COMP%]{\n    position: relative;\n    display: block;\n    width: 100%;\n    background-color: lightblue;\n}\n\n.form-control[_ngcontent-%COMP%] {\n    width: 100% !important;\n}\n\n.DivLogo[_ngcontent-%COMP%]{\n\n    background-color: lightblue;\n    padding: 15px 15px;\n    border: 2px solid lightblue;\n\n}\n.DivHeader[_ngcontent-%COMP%]{\n    position: relative;\n}\ndiv.bodycard[_ngcontent-%COMP%]{\n    position: relative;\n}\n\n\n\n.errorMessages[_ngcontent-%COMP%]{\n\n    color: red;\n    font-size: 1.1em;\n    width: 100%;\n    margin-left: 1px;\n   \n\n}\n.ng-invalid[_ngcontent-%COMP%]:not(form){\n    border-left: 5px solid #a94442;\n}'];
//# sourceMappingURL=form.component.css.shim.ngstyle.js.map