/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['.badge[_ngcontent-%COMP%]{\n\n  \n}\n\ndiv.selected2[_ngcontent-%COMP%] {\n    background-color: #33cccc;\n    \n}\ndiv.selected[_ngcontent-%COMP%]{\n    background-color: #009999;\n}\na[_ngcontent-%COMP%]{\n    text-decoration: none;\n}\n\n\n.custom[_ngcontent-%COMP%]{\n    cursor: pointer;\n    display: inline-block;\n   height: 40px; \n    width: 40px;\n    margin: 2px;\n  background-color: #33cccc;\n   \n}\nspan[_ngcontent-%COMP%]{\n    position: relative;\n    top: 50%;\n    left: 50%;\n    float:left;\n\n    transform: translate(-50%, -50%);\n}\n.custom2[_ngcontent-%COMP%]{\n\n   height: 40px; \n    width: 100px;\n    margin: 2px;\n  background-color: #33cccc;\n}\n.alignPagination[_ngcontent-%COMP%]{\n    float: right;\n}'];
//# sourceMappingURL=pagination.component.css.shim.ngstyle.js.map