/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['#wb-cont[_ngcontent-%COMP%]{\n    border-bottom: 1px solid #af3c43;\n    font-size: 34px;\n    margin-bottom:.2em;\n    margin-top:1.25em;\n    padding-bottom: .2em;\n}'];
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map