/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['.modalContent[_ngcontent-%COMP%] {\n    background-color: rgba(0, 0, 0, .2);\n    \n    position: fixed;\n    padding:0;\n    margin:0;\n\n    top:0;\n    left:0;\n\n    width: 100%;\n    height: 100%;\n    z-index: 100;\n   -webkit-font-smoothing: antialiased !important;\n    \n}\n.modalHeader[_ngcontent-%COMP%]{\n    width: 100%;\n    height: 3%;\n    \n    font-size: 2em;\n    margin-bottom: 10px;\n    font-weight: bold;\n    margin-left: 10px;\n}\n\n.modalMain[_ngcontent-%COMP%]{\n    background-color: #fefefe;\n    top: 20%;\n    left:50%;     \n    position: absolute;\n    transform: translate(-50%,-50%);\n    width: 80%;\n    \n    margin: auto;\n\n    -webkit-transform: translate3d(-50%,0,0) !important;\n    transform: translate3d(-50%,0,0) !important;\n    \n    \n \n\n}\n.modalFooter[_ngcontent-%COMP%]{\n    float: right;\n    \n}\nmd-icon[_ngcontent-%COMP%]{\n    cursor: pointer;\n}\n.modalBody[_ngcontent-%COMP%]{\n    max-height: 80%;\n    overflow: auto;\n    z-index: 102;\n\n}'];
//# sourceMappingURL=modal-box.component.css.shim.ngstyle.js.map