/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/app/forms/salesForm/sales-form.module';
import * as i2 from '../../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/forms';
import * as i4 from '@angular/cdk';
import * as i5 from '@angular/platform-browser';
import * as i6 from '@angular/common';
import * as i7 from '@angular/material';
import * as i8 from '../../../../../src/app/shared/shared.module';
import * as i9 from '../../../../../src/app/pagination/pagination.model';
export const SalesFormModuleNgFactory:i0.NgModuleFactory<i1.SalesFormModule> = i0.ɵcmf(i1.SalesFormModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MdDialogContainerNgFactory,i2.MdDatepickerContentNgFactory]],[3,
              i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i3.FormBuilder,
          i3.FormBuilder,([] as any[])),i0.ɵmpd(4608,i3.ɵi,i3.ɵi,([] as any[])),i0.ɵmpd(6144,
          i4.DIR_DOCUMENT,(null as any),[i5.DOCUMENT]),i0.ɵmpd(4608,i4.Directionality,
          i4.Directionality,[[2,i4.DIR_DOCUMENT]]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,
          [[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i4.Platform,i4.Platform,([] as any[])),i0.ɵmpd(5120,
          i7.ScrollDispatcher,i7.ɵe,[[3,i7.ScrollDispatcher],i0.NgZone,i4.Platform]),
          i0.ɵmpd(5120,i7.ViewportRuler,i7.ɵc,[[3,i7.ViewportRuler],i7.ScrollDispatcher]),
          i0.ɵmpd(4608,i7.ScrollStrategyOptions,i7.ScrollStrategyOptions,[i7.ScrollDispatcher,
              i7.ViewportRuler]),i0.ɵmpd(5120,i7.FocusOriginMonitor,i7.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,
              [[3,i7.FocusOriginMonitor],i0.NgZone,i4.Platform]),i0.ɵmpd(4608,i4.InteractivityChecker,
              i4.InteractivityChecker,[i4.Platform]),i0.ɵmpd(4608,i4.FocusTrapFactory,
              i4.FocusTrapFactory,[i4.InteractivityChecker,i4.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i4.LiveAnnouncer,i4.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i4.LiveAnnouncer],
              [2,i4.LIVE_ANNOUNCER_ELEMENT_TOKEN],i4.Platform]),i0.ɵmpd(5120,i7.OverlayContainer,
              i7.ɵa,[[3,i7.OverlayContainer]]),i0.ɵmpd(4608,i7.ɵt,i7.ɵt,[i7.ViewportRuler]),
          i0.ɵmpd(4608,i7.Overlay,i7.Overlay,[i7.ScrollStrategyOptions,i7.OverlayContainer,
              i0.ComponentFactoryResolver,i7.ɵt,i0.ApplicationRef,i0.Injector,i0.NgZone]),
          i0.ɵmpd(4608,i5.HAMMER_GESTURE_CONFIG,i5.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(4608,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(5120,i0.APP_ID,
              i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i5.DomSanitizer,
              i5.ɵe,[i6.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i5.DomSanitizer]),
          i0.ɵmpd(5120,i5.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i5.ɵDomEventsPlugin(p0_0),new i5.ɵKeyEventsPlugin(p1_0),new i5.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i6.DOCUMENT,i6.DOCUMENT,i6.DOCUMENT,i5.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i5.EventManager,i5.EventManager,[i5.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i5.ɵDomSharedStylesHost,i5.ɵDomSharedStylesHost,[i6.DOCUMENT]),
          i0.ɵmpd(4608,i5.ɵDomRendererFactory2,i5.ɵDomRendererFactory2,[i5.EventManager,
              i5.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i5.ɵDomRendererFactory2]),i0.ɵmpd(6144,i5.ɵSharedStylesHost,(null as any),
              [i5.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i5.Meta,i5.Meta,[i6.DOCUMENT]),i0.ɵmpd(4608,
              i5.Title,i5.Title,[i6.DOCUMENT]),i0.ɵmpd(4608,i6.CurrencyPipe,i6.CurrencyPipe,
              [i0.LOCALE_ID]),i0.ɵmpd(4608,i7.MdDialog,i7.MdDialog,[i7.Overlay,i0.Injector,
              [2,i6.Location],[3,i7.MdDialog]]),i0.ɵmpd(4608,i7.MdDatepickerIntl,i7.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(512,i3.ɵba,i3.ɵba,([] as any[])),i0.ɵmpd(512,
              i3.ReactiveFormsModule,i3.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,
              i3.FormsModule,i3.FormsModule,([] as any[])),i0.ɵmpd(512,i7.CompatibilityModule,
              i7.CompatibilityModule,([] as any[])),i0.ɵmpd(512,i4.BidiModule,i4.BidiModule,
              ([] as any[])),i0.ɵmpd(256,i7.MATERIAL_SANITY_CHECKS,true,([] as any[])),
          i0.ɵmpd(512,i7.MdCommonModule,i7.MdCommonModule,[[2,i5.DOCUMENT],[2,i7.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i7.MdCardModule,i7.MdCardModule,([] as any[])),i0.ɵmpd(512,i6.CommonModule,
              i6.CommonModule,([] as any[])),i0.ɵmpd(512,i7.MdProgressBarModule,i7.MdProgressBarModule,
              ([] as any[])),i0.ɵmpd(512,i4.PlatformModule,i4.PlatformModule,([] as any[])),
          i0.ɵmpd(512,i7.MdInputModule,i7.MdInputModule,([] as any[])),i0.ɵmpd(512,
              i7.ScrollDispatchModule,i7.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i7.MdRippleModule,i7.MdRippleModule,([] as any[])),i0.ɵmpd(512,i7.StyleModule,
              i7.StyleModule,([] as any[])),i0.ɵmpd(512,i7.MdButtonModule,i7.MdButtonModule,
              ([] as any[])),i0.ɵmpd(512,i4.A11yModule,i4.A11yModule,([] as any[])),
          i0.ɵmpd(512,i4.PortalModule,i4.PortalModule,([] as any[])),i0.ɵmpd(512,i7.OverlayModule,
              i7.OverlayModule,([] as any[])),i0.ɵmpd(512,i7.MdSidenavModule,i7.MdSidenavModule,
              ([] as any[])),i0.ɵmpd(512,i7.MdSelectionModule,i7.MdSelectionModule,
              ([] as any[])),i0.ɵmpd(512,i7.MdOptionModule,i7.MdOptionModule,([] as any[])),
          i0.ɵmpd(512,i7.MdSelectModule,i7.MdSelectModule,([] as any[])),i0.ɵmpd(512,
              i7.MdSliderModule,i7.MdSliderModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,
              i5.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any) => {
            return [i5.ɵc(p0_0,p0_1)];
          },[[2,i5.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i5.BrowserModule,i5.BrowserModule,[[3,i5.BrowserModule]]),i0.ɵmpd(512,
              i8.SharedModule,i8.SharedModule,([] as any[])),i0.ɵmpd(512,i9.PaginationModelModule,
              i9.PaginationModelModule,([] as any[])),i0.ɵmpd(512,i7.MdDialogModule,
              i7.MdDialogModule,([] as any[])),i0.ɵmpd(512,i7.MdDatepickerModule,i7.MdDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i1.SalesFormModule,i1.SalesFormModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcm9tYXJpby9hbmd1bGFyYXBpL3NyYy9hcHAvZm9ybXMvc2FsZXNGb3JtL3NhbGVzLWZvcm0ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvcm9tYXJpby9hbmd1bGFyYXBpL3NyYy9hcHAvZm9ybXMvc2FsZXNGb3JtL3NhbGVzLWZvcm0ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
