"use strict";
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.styles = ['td[_ngcontent-%COMP%], th[_ngcontent-%COMP%] {\n    padding: 9px;\n    border: none;\n}\nth[_ngcontent-%COMP%]{\n    text-align: left;\n\n}\ntr[_ngcontent-%COMP%]:nth-child(odd){\n    background-color: #f0f5f5;\n}\n\n\nth[_ngcontent-%COMP%]:last-child, td[_ngcontent-%COMP%]:last-child{\nborder-right: 1px solid lightgray;\nborder-left:1px solid lightgray;\n\n}\nth[_ngcontent-%COMP%]:first-child, td[_ngcontent-%COMP%]:first-child{\nborder-left: 1px solid lightgray;\n}\ntable[_ngcontent-%COMP%]{\n    border-collapse: collapse;\n}\ntr[_ngcontent-%COMP%]:last-child, th[_ngcontent-%COMP%]{\n  border-bottom:   1px solid lightgray;\n}\n.displayTables[_ngcontent-%COMP%]{\n    margin-bottom:124px;\n}\ntr[_ngcontent-%COMP%]{\n        border-bottom: 1px solid lightgray;\n}\nth[_ngcontent-%COMP%]{\n    width:30%;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcm9tYXJpby9hbmd1bGFyYXBpL3NyYy9hcHAvdmlld3Mvdmlld1NhbGVzL3ZpZXctc2FsZXMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3JvbWFyaW8vYW5ndWxhcmFwaS9zcmMvYXBwL3ZpZXdzL3ZpZXdTYWxlcy92aWV3LXNhbGVzLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
//# sourceMappingURL=view-sales.component.css.shim.ngstyle.js.map